name: Cluster Deploy

on:
    workflow_dispatch:

jobs:
  Deploy-Cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Create EKS Cluster
      uses: bitovi/github-actions-deploy-eks@v0.1.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_eks_cluster_admin_role_arn: ${{ secrets.AWS_ROLES_ARN_SERVICE_EKS_SANDBOX }}
        tf_stack_destroy: true
        tf_state_bucket_destroy: true 
