name: Helm Deploy
on:
  workflow_dispatch:

jobs:
  Helm-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}  # the branch name
    steps:
      - id: Deploy-Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
            aws-region: us-east-1
            cluster-name: bitovi-deploy-eks-action-tester-main-cluster           # created by the deploy-eks action
            cluster-role-arn: arn:aws:iam::755521597925:role/aws-reserved/sso.amazonaws.com/us-east-2/AWSReservedSSO_AdministratorAccess_402f22a297379e03
            chart-repository: oci://ghcr.io/
            chart-path: nginxinc/charts/nginx-ingress
            namespace: ingress
            name: demo
            version: 1.2.2
